#!/bin/sh

# Default to debug (specify --release for release-mode)
if [ $# -eq 0 ] || [ $1 != "--release" ]; then
    # Debug
    rm -rf build-debug # Clean
    CC=clang CXX=clang++ cmake -B build-debug # Configure
    time CC=clang CXX=clang++ cmake --build build-debug --target mesh2audio -- -j 8 # Build
else
    # Release
    rm -rf build-release # Clean
    CC=clang CXX=clang++ cmake -B build-release -D CMAKE_BUILD_TYPE=Release # Configure
    time CC=clang CXX=clang++ cmake --build build-release --target mesh2audio -- -j 8 # Build
fi
