#!/bin/sh

gfortran -c src/precmod.f90
gfortran -c src/stringmod.f90
gfortran -c src/m_global_parameters.f90
gfortran -c src/m_data_input_output.f90
gfortran -c src/m_math.f90
gfortran -c src/m_finite_elements.f90
gfortran -c src/p_main.f90

gfortran precmod.o stringmod.o m_global_parameters.o m_math.o m_data_input_output.o \
    m_finite_elements.o p_main.o -o fem

rm -rf src/*.o src/*.mod
rm -rf *.o *.mod